[build]
  publish = "."

[[headers]]
  for = "/static/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/uploads/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"


